---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: check-out
spec:
  encryptedData:
    password: AgAmAzFFBehr6eXEoib0xwp4FBOulM6Zl9p2A0wUFKUZmHfq+M89aR8+EKdfkn/ognrQFV0rryGbXHRyZiqwrz5TvgXD1K1Eg1zEA4Q4g17R7jaC7/f0T2vB+38uuBhj+VE/hSky3z743qa1bwPnZrPgYnI4e+yCclzt5a1TJcxIRdO2Z34hk13LA5occd9H9Z3VesRRQ2TrF0N4FHKIanVRUAe2fEk6xD2xqRkFt1M8+H4egxZLuj/4JleuV9tkkZqFFlhaj328cmDS8uqKFye0/DvinKz759nnXjTOGBLilmPvgC3U/YgUpFTP+hsa26QBpbLF2afqHzGw0QhR17BSGlKzMc+/NwlMRjT94ZjdOM1vsZzHbWP4OI/QJbrRbl5dD0DrEtKKiwaEo02snVvahRIgrqfskVTPFZaUcU+fNV2lmDxUYuGGVQ+9Md02WZXwOYR3ctUAdmCbPzJpXtXacVh0UcwjKdrSQlHgTllDXGX9++yRZSexCxpFwEjizKe7koMyiuF11pjOXbWy3cmfwig2osRb9q+4loqhy+L+s9S4WdK2cd6+tRn8BEtm5szIX//xutnDlfoKOEbt51MiU9igc5ecZAeHiu8KKDMSgpgJHflAsqQ5SYnpHLgIIayf9NOrd4fx1sMAHLVUWejdV5CpiPujtdNzheC6bLbEd1OO4P/Jqw1sFYhmIvT48js=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: check-out
    type: Opaque
