---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sso-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAmMnKDTiZAVPiHl4w/vIPKOmG5fPjGWo+7zpakyu8tFPLJZVKDgl5vD0RiDf9P2tUUVs9I2F4KbvV5y4R0wKG9eSB36l7o2nlAL1H1yAi/I29t/ZL1xOAUF6vGe6IfGiQvAly3jtAo9/Sr5yqihbBbF6R2QObbc7OlZ88CpiHIoYAKBImOqeUKpYRf9QFC+WMfEedjK4qTQiUeG+RCdN82PgUNKJWJX/IFomMLabdruSJk29LfmcUAw7Wa1kKRJ/OQoOuA0Z0DK23BTQp6xtATg9l25H+U4ew5ueFBWSktRczbfUGz6K0nYLen8SizGMCMmNRvEXujfU+HUbZuvX2Neav3q9QphoLB2Ix2YEufa2/Z8sw31Vla594Mvpn94ggYzqAFZ10qZz8cAoNa8AMuglj8Wcfr08heJmP+sGEgMYNrLMjtYUZBGzOnAFBZcxmoFsSjx40KPr2+rFLtblKtcN1DxqIlE6OV6DYMmsJL5MZfprUf+LU9oX24QpIHRMnAoVTCosvw1Z1OZyRyJDsbJapqHz672XD/YwAq+L4Eyh8acRz82rv7hrnPo+Nd/MXOSix9KEBUTTyo1LcGhaixpYdRQa/n3z2ZGnlB8/D95/wKHB9J9yxlXnq1EXw1TfK+wlEfjMbo0BWVAkOSo3WgITu5xMOyoXqCrHa0lfAHh8KCjtASqCej2PsI1cDvr/WHM119hAA21msZGXUj7OCDaJL0tr0f0bPjEc4G6A/sCSB6hKndSeTM
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: sso-secret
      namespace: argocd
    type: Opaque
