---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-secret
  namespace: check-out
spec:
  encryptedData:
    OPENAI_API_KEY: AgCq1hChxTDfe2xrSz9lX3MBtfBaJ2VljdyxNOCnXUNuhvtNQPHp/6V5U97O/xOXH0LBrLgTkCB0DoecfYP0srQltpL6MZlNubjeqGolhkKnC3PR0V63LhPF0+tGPKXK0Y3wQuD9UojwI9WcoekHdSIu9p+hQZwf/a3wMla5nJ20LxOCRgsXKcSIh1yUBG0pNRrZmzqBmzNzjNsHl4NLLE08hclcN56xvommJqQrodgUnm0LFPvGeDA3DXKMlK4Fj+y1VznL5JfLrkCaDqZ4P6SbJiV4O6belS/0GJzZ69k/WlY02OFdWzdXHE0Erj1tHrIFcEQlyBSeCd2dkD7Xm6q+PQVmvJoaXp59O0IJZHACl/tQbgyZpkMeehg/kHKRIaHV/c3VLfjnfTsfig+TOLRxTyAblnhKp+V9rcnYBCAeqH8GBienPK7f6IYemvnbKZqsnhsN8PZdYdcMnjm658iuZDXJDf8NvTmG3K+kwnknyqo0zZvjJ3xA/kNHFZDzTHRkLmMNSVBS8+zUOjADWSdJZGCAQJzCVJk72pzDR/XiNHYFREnompzfIFJtz0ulNk3oYArEZOLeU6GREoPxdQc02GD8EFFytCY+JzCh92Ci3BJH+BcR4mZOnQi5sknIUehPiBQheBvUOWrmseZFJgIIcTaR1IvaObc91rkzIZ8oBiLSXNVc02LyHxjoeOd4wkJn/o+QZ31ZaL0iNLVDdNLKyjqd3HdNCR62zVR1iMPT3WeqPfaohRKA5sKo0LxLdXcxhfRbiVogRA==
  template:
    metadata:
      creationTimestamp: null
      name: ai-secret
      namespace: check-out
    type: Opaque
