apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: check-out-stg-be-ingress
  namespace: check-out
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: check-out-check-out-redirect-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: api.check-out.paperst.ar
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: check-out-stg-be
            port: 
              number: 80
  tls:
  - secretName: api-check-out-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: check-out-stg-ai-be-ingress
  namespace: check-out
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: check-out-check-out-redirect-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: ai.check-out.paperst.ar
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: check-out-stg-ai
            port: 
              number: 80
  tls:
  - secretName: ai-check-out-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: check-out-minio-ingress
  namespace: check-out
  labels:
    name: check-out-minio-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: minio.check-out.paperst.ar
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port: 
              number: 9000
  tls:
  - secretName: minio-check-out-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: check-out-minio-ui-ingress
  namespace: check-out
  labels:
    name: check-out-minio-ui-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: minio-dashboard.check-out.paperst.ar
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port: 
              number: 9001
  tls:
  - secretName: minio-dashboard-check-out-tls

