apiVersion: v1
kind: Service
metadata:
  name: check-out-stg-be
  namespace: check-out
  labels:
    name: check-out-stg-be
    env: stg
spec:
  type: ClusterIP
  selector:
    name: check-out-stg-be
    env: stg
  ports:
  - port: 80
    targetPort: 8000
    name: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-out-stg-be
  namespace: check-out
  labels:
    name: check-out-stg-be
    env: stg
spec:
  replicas: 3
  revisionHistoryLimit: 1
  minReadySeconds: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      name: check-out-stg-be
      env: stg
  template:
    metadata:
      labels:
        name: check-out-stg-be
        env: stg
    spec:
      containers:
      - name: check-out-stg-be
        image: nginxdemos/hello
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi