---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sso-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgANdr7o5rdWBSBH53nBYGCAZPBeQZb6JFCXSVr5ycngdAIzmbISAe5w7gYMItLHu+dDbZb7mCZTcuDgB2b0F3m0Kf/Xcn+PKwsqolxUGuTo2yAS2+tBpKK7rPQ+QWBsbejtdBkT+3KbCiHmS9BE3Eyj/TUDSZSDAlo4RcRIWuIX1Pr1156HIN21E97KSlc0OXsktz4I4ncYxs9OkliRkdD6EAvvRIC0Z8NDN/ewKx414Hc8cJBPZf9xGGZ8vzbemQakG+/zMvu74+f6bh6TjXVn/SU8k/Bttxu21M1sCZWi5ugH0nSLE3D0dDZjmTbzHv7TELTGTWCM3UYWekTs/oxAuwT3iiAiYlufvnCgySo2dN5YGZEZMUAOLFSLlXB6mXEmhwtSj/JNIwlD+287xr9d15yar7YfKd1fcZtyjUVCiFRf1jqbPvCxrDOtTAbCA6sE8knobzqGYE6VbHqGSsuiOgvDT7Y1roPLKTsI1ix08T0IEcHkZbuyWcRGdTNWByPvwDO8wGkmZdtb8I3ebwPCtXLwzVV48wyRYMgx0dDifxk8OqKxi+hvke+dqqV0aTsjNNwTeWxyMgCpRm2kfh0/6mFfIPhbRU3Zz+iGhS2Zou0OQtAL4eTpwIQ0xcaBs2M0s++mH9Vb8qHVSq+hTbpS+wBMeHfVrkiriClMTkL/lYMMdV9/g1GKPOeV8zKQYS82qh28DKzWONS2IAqP08FodrYpPQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: sso-secret
      namespace: argocd
    type: Opaque
