---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sso-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgC86MHnMuA1+yb6VBLMWQPQ9h9ynOxALQQ6yIIj6fLPXztvqnP/+y5svF74yl/KIj3yKNEFQrsIQRpuqhJTWmAVCS4wt1ZgElM3uBoAQqIcpgx4IQ8XmdzQYXA87h8ybLEs5ggylxOS1snLxNebvtjVpSfg0iaPMR9hcrz+fqKCR6EBBQ5UoyEkihpHDY6nwdPaD45v9KLGlo90PhgnLGeJDK2YIl+1v/G+1N1sCQNiiuTdo2Y5NzVOUa0qtcoxbPjveXJ06nxD35E/Xt7XhPfX7lVH/2Rar8ueJ+7W65EeFvOiCxW+thQCDJXyhJTlDK9t+JH1H4kK8QzOK16+R/6/Xa2MZ4crF2qC0sjFaEGST5DBNmCJRtbLYU3cAsqs76Yo+f84qfPpxIggrYEUgRiVeV4JHev3j3Spux25Fx3DU7lOrAlXQiovDTVuWcHNnvqLXNGmLTuLV6wl7cfg++dgoyMa1snvez+8AvfKP+WSC0JkQlYfKnS6GtgNx1b0f8pVzRydK7NSZlEKk18dEYPcRBMThov/YU7GQT90c1BocuPZcCNBE4rwCrv5nvk69dae4K0VezdrAvz0dGupyT5rmKGvBo0V7IVR35DPGSVamEbC7xEHbRsPyEPQLDxDxG22rJl0KqSK2aoUHGdF7XqJqJR/D1e4csNu+YBuWPuI8R7LfUCrcpdg3f14qsyQYd79WJLv1szOPdtx2HsdUHM7kdzD0A==
  template:
    metadata:
      creationTimestamp: null
      name: sso-secret
      namespace: argocd
    type: Opaque
