apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  project: default

  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.14.5
      helm:
        releaseName: cert-manager
        parameters:
          - name: startupapicheck.timeout
            value: "5m"
            forceString: true
          - name: installCRDs
            value: "true"

    - repoURL: git@github.com:hot-spicy-buffalo-wing/check-out-gitops.git
      directory:
        jsonnet: {}
        recurse: true
      path: cert-manager
      targetRevision: HEAD

  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
