---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: check-out
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - path: check-out
    repoURL: git@github.com:hot-spicy-buffalo-wing/check-out-gitops.git
    targetRevision: HEAD
    helm:
      releaseName: check-out
      valueFiles:
      - $myRepo/check-out/values.yaml
  - repoURL: git@github.com:hot-spicy-buffalo-wing/check-out-gitops.git
    ref: myRepo
    path: applications/check-out
    targetRevision: HEAD
    directory:
      jsonnet: {}
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: check-out
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---


