apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-check-out-tls
  namespace: cert-manager
spec:
  secretName: api-check-out-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "api.check-out.paperst.ar"
  dnsNames:
    - "api.check-out.paperst.ar"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "check-out,default" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "check-out" # Control auto-reflection namespaces
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-check-out-tls
  namespace: cert-manager
spec:
  secretName: ai-check-out-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "ai.check-out.paperst.ar"
  dnsNames:
    - "ai.check-out.paperst.ar"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "check-out,default" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "check-out" # Control auto-reflection namespaces
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-check-out-tls
  namespace: cert-manager
spec:
  secretName: minio-check-out-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "minio.check-out.paperst.ar"
  dnsNames:
    - "minio.check-out.paperst.ar"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "check-out,default" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "check-out" # Control auto-reflection namespaces
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-dashboard-check-out-tls
  namespace: cert-manager
spec:
  secretName: minio-dashboard-check-out-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "minio-dashboard.check-out.paperst.ar"
  dnsNames:
    - "minio-dashboard.check-out.paperst.ar"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "check-out,default" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "check-out" # Control auto-reflection namespaces