---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDMTZbEKDfU32zneNtOroLW1aO4QBB2oAKc3VHIR3frC1H22BgLrDtZGaBIJAjmrhrGR1BI0qgwNm/EERRpO6kwH2tdtDClwGmLMcP6UpAOD0VPQJ78/t1fGecGNz4ZKos9JPzQJt4Y+iq4Ec+NGcYxd+0s0DvHiYg+xMcsjvIQs71YOl7LiX+74hLDIpK2No0w69U6W4FZYbOOa/NW6VDxMGR1zVv6TPqF8lU0pPQj/rocyS+rgzoqLiIHgVZGFzKRk9AF9L4gWnjbodabxHuJtlaw+lBjfGZY4WKyrFVUoUvbhYeJlJBJFbyTp/mPrW5FvuXgC6aIsDviWzd9hBHmlPWmTNUr5St5orhL8bpm5FmCbIDF0zZLiQAJDCpybtBHlLxmNpw/FOvdLvd0Oz0k/zYXCPDHmPQGXUnQB1DqGTLRZqvuh3PhZF2f8lyfx9FusK/jlaP+ujp9DeaMCOvk1jdhE+ia7JPRxfJkoM2HtISJdKCyastBeIAMmbHNEmCyFelcq+GboxYngZ+75a0ktiZ+7kH8rwmNvcL13zDV0Csnx/tPKUu/dDnWSPSJjmUtQTRRReK2GnIohk6g645zJh18ovgzhSaeAG6LAMTeWvu7OHBz/mjiKpBe+XT308NeJf35N1QMaikHtAWZsEFgxDt07uSa3Sey6en736RD/ysY4WYhnrvQlEtQgEkyVOoqZNuPy/seVxe1dPaAX1uTY7B3eaR4joUXkfjZqguOUdVcP235iw21F+G5ZMG80S06PT32Dn5u1eI=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
