---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBXunKKF7b8teCuxw4VIsk1QlLHodQzXoXXWHy15xesdVtz4hy3HrBwSf3ir9eNV19I5yoSzIArM7RDdtvgLQojs8PYVCQ+AHg42QajwQXYtQHytA1nqtw0WgSB17ViaehhLdKNpxUQb6fUJW1qeFfaOYa8J24IcUieKyzTIMA2gDTHyMn/Txor26+7UKId8xEPP+E4iYV1nHIaT0do7/fAl7N0zYSNOt/6M3XGBt271FJiPdnhZQUNTP4f2f6LHijKO1WtvK1dMp7fG3WKASopH2zO8YETRAsSTO78HHSbACmavJHczgUPSCxk8sBpNtP0qWJMiulCGq0zZEcHqZsrhpMc5pctVKpWwRmIXSbowpuDOO78q+VOaeRWPvU5HU0WK/ib8cKlHiy0eZyhnVG3mN2faBhAbh1YqM+hM9/PCRmUdGInDuHf49a+yTeLTj5Lq80vkOtGrnwvP9GzXUU1a9i0MvtdHf77BgmfQinkLKkxGc9aCNqhOKLTz0iRY+HA7ZipLOIPaXn3HlA3EgoA7YRT3gGdTo0dLwYKl4mlx78FSXPZhMgAVAYHlXJpBDrXuaIGDaXY3OBRrqRZBiNpkia3ldASU2iVGcQilH/o/OBreTY7uzmThyepiU1odo9d2i4KCG7oOFZCwKVtkVdbik6w0G0mRAtF6Vb+GnzbwyizVSIVi7BbMdjcPj5rNc3G8lI8Y4EX+ri8ipo/TPcSkvGqeatP1vYlCl7gRcPG3tCMRfbZ35tI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
