---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    stdin: AgAFi9ikpPcFjuLnpxV7HXqWVPuGuqILf2mKrmO9i9d512kdfy5onZxMetdMR7aGYbUZjApw4EHOW/7bhKC4gT6t8MQUUxmG9w2hZcBXCwLaX1f1dFrlQ36iY6aImr74MEkcG2eHGqs/kUOrVAkiIurEsly6LLYXqSC4PRTa4+HdZUb2mzJOQQIRr9FPWmDATbNOcUAvgODfgNlahe/z8xG4HMVcCrKhdjcckLPi6iEzIuFtThO3rtnqmsCW12kjApRMu09s0AoB4PRNlgBY13PQ6r889zje1gMSyLvvIRi1DDXPcGWIn5DQK4Z0DGVeXtn95TgK2iB3NU1panpxoCe8MjNrIfGIuqTE9TEW6+l+ETEeR0nv7XA9AsG89RK4wHA2+QXSl8lbN+VSJfme8kFw+ITLFcahT8Fs3IUCtJPo2SL/oh2oPGyFz+nuzT9iNTAJIncp9n0mLi6x6zZlNEiNeDxzXBLwoAosjEyyy7m9v4/N7wWFSa2te4IlNGW+7xRtKh2MsMqBZ4JY2LiyQ7/pACzL8g16lgC/Y1DUDzFEWFvO/i+QrHiN4zguwVGp20XZvwRAeh/LvkbwrZAlSlAXKyV9tzycjilfuU+II7sKjbI6jBpKqqDZkoH/TJZIG7ca/rW2fTz/YTmlTsRlQ+OA3BgwZeE/PAsWrfwagkYcYEFgYQ0ZhnNStE0zJhH8b1jZm4Zlw8fQ58z1aeqoV4Ec3SUKW9EH1joC2vsvl8Q6x+sfCr0AJA929vmM/K20WqnUZA/IILzXNPg=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
