---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAFHogKLcFWoM6d7H24/p4RwJnQtuGj4J9iXcPP7rjtexHW+6jjKVeovJwBtqxrWFbDCown4Ls8gA3xjgwU0PDFjkjy2ldOGINzOpqEDGJ0OTcripj+9GTKnfgKIVT+tG+6wkn/OP0uX0L5QiVM0qxXuiaIFxoZ4Cuvb96UCnaOvJg6KydLCEiUzpMgQZfb+30+CvgXW9N+FvgVBdPKDOO/eUyynQQ2Nywns3hAiuvQ+SOlrrfPg4tLDVyjH4zbv4kFA3EvHXvjPzZ6Ygvw9J/90kWxghURfQX9Rc32adVJmPX727BHowCmWoAZQVdgCm/i6WOWmD7KZi49BQE3GTtAZn21QsQrswkvXz1Y+2O9dU3JMCNATxMvjPNsdHfZ2iH325n9/l7hfQKB/Ck/emJ1jc+VxJoE1YBYxUvAovHLBoSan1ttFDZF6/gsOJUXopGHnxzQ1cnHHPOKsyg76c4kB8xrswrwUG9uA6qaX8aXGVWkUvs0FIg3kEUtSGZswAHr6H19oeUcmEd9OJvYo9r6TqejOOsSNNjNeu8sP6Fnc6M+7ehagSCEmUe7Pd0B6zouNQ2ia089P6kR9+B5PbVQmR2MEjGiMZIWoLNRCkef0C5Vaniw7/7TN08jdGdsqniPoiXPkWsHpC4JxRGN6LdioRe0Zd3LWd/itf4vy8mwOzHZx1T3PQmgWJZdd/OoODXbiuzu9hxk+FFOU3Fbk/FzKLum+/tjXQytoIHqefeUTrsjR+RskhxS
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
