---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    stdin: AgDJN0eKXYKV6JieETd5oZ6GeQEJmwJVgbf5uvQeR9NdCqaQmxFVGXpuWt92jqAD+sEOoiSOQWTdLQ1JLRggNzTvDcXA2X+OIXMZV51JVEhXDYd6++EElTuwwbGhO7PGiOfrAPc4ZMZKqb29UVd6/FePD2jw0qVfrdul2MKP4ASDT1pm3T64SjALw1oos1Af216ha/939Ris7WxcCvCbW6rLqI8fTGQz0wQkdAVoaQiALs6LOsNLj3Z+kZbjqptDQ/uungWpqxPBRWYZUewZJFnVFM1PLhmKo2MVV+GLHlr3PJSVHen5bW+mtble0tj/2KDnsA1eLYo7f+dKdplmtpQHKQB7c81BpVWDBNGv0by62cOtOI1x1C3PodpL0a7GYt87XJbgWooGMc9K9m5JLJc7hdGOHEp8iwM/zyVFpE385YTje8JRn6bv8M5pMwQtW7DhgKGMb1DopJSv4nhum0FIInpwT7FeMlPwWa8g4UHQHqKP5+C0/FS+UCgzkRgpSNVZzxzfz5XowQy5rfVqo+ayYDHxng+DA8y2Uz77z/8GbZAnRSspHwgpCro1ZQr5emLJD4nSbyUihd4td3PQzxQpbt+PlbUOSQg9c+Lj5nuQtMmmmHIU/I6JUf4ySWippt6O7ipYvn/JH6cUNbz14lxBB/+tVtnbQVT48QgfjRIQEV+ikLvohy4yX9gvABvCEYBmeeJiWVUcPHv7lQvId8oXY1DjBan0t0z2NBYEr/n9m/PNdy+VknbrS4u3f7vyE+BO0r3Jf/mFfbA=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
